"""Primera migración con dispositivos y claveI

Revision ID: da8d9f4eabfb
Revises: 
Create Date: 2025-06-14 23:33:36.199391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da8d9f4eabfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datos')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(None, ['api_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('api_key')

    op.create_table('datos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dispositivo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('temperatura', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('humedad', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('datos_pkey'))
    )
    # ### end Alembic commands ###
